#!/usr/bin/env python3
"""
build_examples.py — run the three worked examples for real, bundle each into its standalone
deliverable, and write the "From a prompt to a figure" section of the README from one manifest.

    python docs/examples/build_examples.py            # run + bundle + write the README section
    python docs/examples/build_examples.py --no-run   # only rewrite the README section

Per example directory:
    analysis.py            what a session writes against the skill (the CONFIG block + body)
    <id>_standalone.py     what the skill hands over: bundle.py's self-contained script
    log.txt                everything the run printed (the gates)
    figure*.png            the README copies of the figures (long side capped at 1400 px)
    caption.txt            the caption the analysis emitted
    out/                   the run's vector masters + tables (git-ignored, regenerated by the script)
"""
import os
import re
import sys
import html
import shutil
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))                           # the skill root
BUNDLE = os.path.join(ROOT, "bundle.py")

EXAMPLES = [
    dict(id="bmc_lod",
         prompt="Doxorubicin peak areas from Bansal 2021, transmittance mode, 0.6–1.4 % w/w. Fit the "
                "calibration, give me LOD and LOQ, and read off the concentration for peak areas of 3.5 and 6.0 mm².",
         figures=[("out/bmc_dox_calibration.png", "figure.png")],
         did=[],
         ),
    dict(id="cif_report",
         prompt="Here is aspirin's CIF (COD 7247819). Validate it, calculate its Cu Kα powder pattern, "
                "and give me an ORTEP view with the hydrogen bonds.",
         figures=[("out/pxrd.png", "figure_1.png"), ("out/structure_ellipsoid.png", "figure_2.png")],
         did=[],
         ),
    dict(id="pectin_calibration",
         prompt="Six pectin calibration standards as CSV (DM 3–70 %). Give me a publication figure of the "
                "carbonyl region and the ester/(ester+carboxylate) band-area calibration, with the LOD.",
         figures=[("out/pectin_calibration.png", "figure.png")],
         did=[],  # filled from the log — see DID below
         ),
]

# "what the skill did": three short lines per example, each quoting the log
DID = {
    "bmc_lod": [
        "fit, 95 % bands and the mandatory residual panel from the published table",
        "<code>{lod}</code>",
        "read-back of 6.0 mm²: <code>{refused}</code>",
    ],
    "cif_report": [
        "validated before drawing anything: <code>{density}</code>",
        "Cu Kα pattern from a Mo-refined CIF, independently cross-checked: <code>{crosscheck}</code>",
        "ORTEP at 50 % probability, C–H hidden, heteroatoms labelled, the hydrogen bond drawn",
    ],
    "pectin_calibration": [
        "every file gated on ingest: <code>{check_trace}</code>",
        "one shared baseline for the two overlapping bands, split at 1700 cm⁻¹",
        "and it says when a method is weak: <code>{bias}</code>",
    ],
}
# log lines the DID placeholders quote (first match wins), shortened for the row
QUOTES = {
    "check_trace": (r"DM3: \d+ pts.*", 80),
    "lod": (r"LOD .*", 70),
    "refused": (r"REFUSED: .*", 140),
    "crosscheck": (r"cross-check.*", 90),
    "density": (r"density \(i\)=.*", 80),
    "bias": (r"p=\S+ -> .*", 80),
}


def run(cmd, cwd):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    return r.returncode, (r.stdout or "") + (r.stderr or "")


def build(ex):
    d = os.path.join(HERE, ex["id"])
    log = []
    rc, out = run([sys.executable, "analysis.py"], d)
    log.append(f"$ python analysis.py\n{out.rstrip()}\n[exit {rc}]")
    if rc != 0:
        print(f"  FAIL {ex['id']} analysis.py\n{out[-2000:]}")
    sa = f"{ex['id']}_standalone.py"
    rc2, out2 = run([sys.executable, BUNDLE, "analysis.py", "-o", sa], d)
    log.append(f"$ python bundle.py analysis.py -o {sa}\n{out2.rstrip()}\n[exit {rc2}]")
    rc3, out3 = run([sys.executable, sa], d)
    tail = "\n".join(ln for ln in out3.rstrip().splitlines() if "timestamp" not in ln)[-600:]
    log.append(f"$ python {sa}      # the handed-over script, re-run on its own\n{tail}\n[exit {rc3}]")
    text = "\n\n".join(log)
    open(os.path.join(d, "log.txt"), "w", encoding="utf-8", newline="\n").write(text + "\n")
    # README copies of the figures
    from PIL import Image
    for src, dst in ex["figures"]:
        im = Image.open(os.path.join(d, src)).convert("RGB")
        cap = 1400
        if max(im.size) > cap:
            s = cap / max(im.size)
            im = im.resize((round(im.width * s), round(im.height * s)), Image.LANCZOS)
        im.save(os.path.join(d, dst), optimize=True)
    print(f"  {'ok  ' if rc == rc2 == rc3 == 0 else 'FAIL'}  {ex['id']}")


def _quote(log, key):
    pat, n = QUOTES[key]
    m = re.search(pat, log)
    if not m:
        return "(not found in log)"
    s = m.group(0).strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def _trim_log(log, max_lines=60):
    lines = [ln.rstrip() for ln in log.splitlines()]
    keep = [ln for ln in lines if ln.strip() and not ln.lstrip().startswith("[INFO] orientation")
            and "timestamp seems very low" not in ln]
    if len(keep) > max_lines:
        keep = keep[: max_lines - 1] + ["… (truncated; the full log is docs/examples/<id>/log.txt)"]
    return "\n".join(keep)


def write_readme(examples):
    p = os.path.join(ROOT, "README.md")
    s = open(p, encoding="utf-8").read()
    a, b = "<!-- examples:start -->", "<!-- examples:end -->"
    if a not in s:                                                     # first time: after the gallery
        g = "<!-- gallery:end -->"
        s = s.replace(g, g + "\n\n" + a + "\n" + b, 1)
    rows = []
    for ex in examples:
        d = os.path.join(HERE, ex["id"])
        log = open(os.path.join(d, "log.txt"), encoding="utf-8").read()
        did = [line.format(**{k: html.escape(_quote(log, k)) for k in QUOTES}) for line in DID[ex["id"]]]
        rel = f"docs/examples/{ex['id']}"
        figs = "".join(f'<a href="{rel}/{dst}"><img src="{rel}/{dst}" width="{100 // len(ex["figures"])}%" '
                       f'alt="{html.escape(ex["id"])}"></a>' for _, dst in ex["figures"])
        rows.append(
            f'<tr>\n<td width="46%" valign="top">\n'
            f'<p><b>“{html.escape(ex["prompt"])}”</b></p>\n'
            f'<p><sub>WHAT THE SKILL DID</sub><br>\n' + "<br>\n".join(f"· {x}" for x in did) + '</p>\n'
            f'<p><sub>WHAT YOU GET</sub><br>\n'
            f'<a href="{rel}/{ex["id"]}_standalone.py">one self-contained script</a> · '
            f'<a href="{rel}/{ex["figures"][0][1]}">the figure</a> · '
            f'<a href="{rel}/caption.txt">its caption</a></p>\n'
            f'<details><summary>full log</summary>\n<pre>{html.escape(_trim_log(log))}</pre></details>\n'
            f'</td>\n<td width="54%" valign="top">{figs}</td>\n</tr>')
    section = (
        "## From a prompt to a figure\n\n"
        "Three prompts, run in this repository with the skill loaded. Left: the prompt and the gates that "
        "fired on the way. Right: what came back. Every run hands over one self-contained script that "
        "regenerates its figure, and the caption is interpolated from the computed values, never typed.\n\n"
        "<table>\n" + "\n".join(rows) + "\n</table>\n")
    s = s[: s.index(a) + len(a)] + "\n" + section + s[s.index(b):]
    open(p, "w", encoding="utf-8", newline="\n").write(s)
    print(f"  README section: {len(examples)} examples")


def main():
    if "--no-run" not in sys.argv:
        print("examples:")
        for ex in EXAMPLES:
            build(ex)
    write_readme(EXAMPLES)


if __name__ == "__main__":
    main()
